"""empty message

Revision ID: 03d636bbc8b5
Revises: 5b4528ccd55e
Create Date: 2021-03-22 12:34:24.699992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03d636bbc8b5'
down_revision = '5b4528ccd55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.String(length=15), nullable=True))
    op.add_column('user', sa.Column('current_login_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('current_login_ip', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login_ip', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('login_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_column('user', 'lastsession')
    op.drop_column('user', 'status')
    op.drop_column('user', 'pkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pkey', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('user', sa.Column('status', mysql.VARCHAR(length=15), nullable=True))
    op.add_column('user', sa.Column('lastsession', mysql.DATETIME(), nullable=True))
    op.drop_column('user', 'password')
    op.drop_column('user', 'login_count')
    op.drop_column('user', 'last_login_ip')
    op.drop_column('user', 'last_login_at')
    op.drop_column('user', 'current_login_ip')
    op.drop_column('user', 'current_login_at')
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
