"""empty message

Revision ID: 26fb7bff7351
Revises: 06d1fb1cb732
Create Date: 2021-03-22 19:22:45.652203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26fb7bff7351'
down_revision = '06d1fb1cb732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('login', table_name='user')
    op.drop_column('user', 'login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', mysql.VARCHAR(length=20), nullable=True))
    op.create_index('login', 'user', ['login'], unique=True)
    # ### end Alembic commands ###
