"""empty message

Revision ID: 29dd38fd1958
Revises: a6396c55d909
Create Date: 2021-03-19 16:57:57.345874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29dd38fd1958'
down_revision = 'a6396c55d909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('tags', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
