"""empty message

Revision ID: 5ab278795c43
Revises: ab3cd959f553
Create Date: 2021-03-22 12:38:59.487092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ab278795c43'
down_revision = 'ab3cd959f553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_column('user', 'password1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password1', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
