"""empty message

Revision ID: 5b4528ccd55e
Revises: fd085bc95a65
Create Date: 2021-03-21 22:36:14.788085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4528ccd55e'
down_revision = 'fd085bc95a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('description', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'group', ['name'])
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['login'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'group', type_='unique')
    op.drop_column('group', 'description')
    # ### end Alembic commands ###
