"""empty message

Revision ID: 7e507da20435
Revises: 9d0e8c1538f9
Create Date: 2021-03-22 12:51:56.252505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e507da20435'
down_revision = '9d0e8c1538f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active1', sa.Boolean(), nullable=True))
    op.drop_column('user', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', mysql.VARCHAR(length=15), nullable=True))
    op.drop_column('user', 'active1')
    # ### end Alembic commands ###
