"""empty message

Revision ID: 828892fa5036
Revises: a194cdda51b5
Create Date: 2021-03-11 19:27:00.416980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828892fa5036'
down_revision = 'a194cdda51b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('issuenum', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('deliverydate', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('isEnabled', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('lastMessageId', sa.Integer(), nullable=True),
    sa.Column('lastsenddate', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuenum')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.drop_table('customer')
    # ### end Alembic commands ###
