"""empty message

Revision ID: 9d0e8c1538f9
Revises: c7d60bd82521
Create Date: 2021-03-22 12:47:07.168630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d0e8c1538f9'
down_revision = 'c7d60bd82521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.String(length=15), nullable=True))
    op.drop_column('user', 'active1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active1', mysql.VARCHAR(length=15), nullable=True))
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
