"""empty message

Revision ID: a9a19a070634
Revises: f507cee5b675
Create Date: 2021-03-23 21:17:38.025103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a19a070634'
down_revision = 'f507cee5b675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_activity', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_activity')
    # ### end Alembic commands ###
