"""empty message

Revision ID: b98edd768afd
Revises: 49c3b9a26d68
Create Date: 2021-03-22 12:37:53.728588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b98edd768afd'
down_revision = '49c3b9a26d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_column('user', 'password1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password1', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
