"""empty message

Revision ID: c7d60bd82521
Revises: 5ab278795c43
Create Date: 2021-03-22 12:46:49.242995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7d60bd82521'
down_revision = '5ab278795c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active1', sa.String(length=15), nullable=True))
    op.drop_column('user', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', mysql.VARCHAR(length=15), nullable=True))
    op.drop_column('user', 'active1')
    # ### end Alembic commands ###
