"""empty message

Revision ID: f507cee5b675
Revises: ebd28dd0fe8c
Create Date: 2021-03-23 15:32:44.612450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f507cee5b675'
down_revision = 'ebd28dd0fe8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_count', sa.Integer(), nullable=True))
    op.drop_column('user', 'l1ogin_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('l1ogin_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'login_count')
    # ### end Alembic commands ###
