"""empty message

Revision ID: f7915683589d
Revises: 7e507da20435
Create Date: 2021-03-22 12:52:10.376170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7915683589d'
down_revision = '7e507da20435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_column('user', 'active1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active1', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
