"""empty message

Revision ID: 192631a7812c
Revises: f6f0a82eb5a9
Create Date: 2021-03-11 19:38:13.639949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192631a7812c'
down_revision = 'f6f0a82eb5a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('issuenum', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('deliverydate', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('isEnabled', sa.String(length=6), server_default='No', nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('lastMessageId', sa.Integer(), nullable=True),
    sa.Column('lastsenddate', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuenum')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
