"""empty message

Revision ID: 4ae3d9086fdb
Revises: 
Create Date: 2021-03-11 18:29:24.949487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ae3d9086fdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('group_membership')
    op.drop_index('login', table_name='employee')
    op.drop_table('employee')
    op.drop_table('changelog')
    op.drop_index('name', table_name='groups')
    op.drop_table('groups')
    op.drop_index('issuenum', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lastname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=100), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('issuenum', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=100), nullable=True),
    sa.Column('deliverydate', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('isEnabled', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=4), server_default=sa.text("'No'"), nullable=False),
    sa.Column('status', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=100), nullable=True),
    sa.Column('lastMessageId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lastsenddate', mysql.DATETIME(fsp=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('issuenum', 'customers', ['issuenum'], unique=True)
    op.create_table('groups',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=30), server_default=sa.text("'Users'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'groups', ['name'], unique=True)
    op.create_table('changelog',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('datecreated', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('createuserid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('post', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('employee',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('createdate', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('login', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('password', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=False),
    sa.Column('status', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=10), nullable=False),
    sa.Column('email', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=30), nullable=True),
    sa.Column('lastlogon', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('login', 'employee', ['login'], unique=True)
    op.create_table('group_membership',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='group_membership_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['employee.id'], name='group_membership_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id', 'group_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('tag')
    # ### end Alembic commands ###
