"""empty message

Revision ID: 9365c53dabd4
Revises: a4e9d02a6ccc
Create Date: 2021-03-11 19:43:40.011796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9365c53dabd4'
down_revision = 'a4e9d02a6ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('tags', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'tags')
    # ### end Alembic commands ###
