"""empty message

Revision ID: a4e9d02a6ccc
Revises: 192631a7812c
Create Date: 2021-03-11 19:41:38.476660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4e9d02a6ccc'
down_revision = '192631a7812c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('tags', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
