"""empty message

Revision ID: f6f0a82eb5a9
Revises: 828892fa5036
Create Date: 2021-03-11 19:36:27.540831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f0a82eb5a9'
down_revision = '828892fa5036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('isEnabled', sa.String(length=6), server_default='No', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'isEnabled')
    # ### end Alembic commands ###
